/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EffectRouteImport } from './routes/effect'
import { Route as IndexRouteImport } from './routes/index'

const EffectRoute = EffectRouteImport.update({
  id: '/effect',
  path: '/effect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/effect': typeof EffectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/effect': typeof EffectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/effect': typeof EffectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/effect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/effect'
  id: '__root__' | '/' | '/effect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EffectRoute: typeof EffectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/effect': {
      id: '/effect'
      path: '/effect'
      fullPath: '/effect'
      preLoaderRoute: typeof EffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EffectRoute: EffectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
